image:
  repository: zetsuboutoshio/otus-demo

host: arch.homework
routePrefix: /otusapp/vtimoshenko

postgresql:
  enabled: true

  fullnameOverride: postgres
  postgresqlUsername: otus
  postgresqlPassword: otus
  postgresqlDatabase: otus

  service:
    type: LoadBalancer
    port: "5432"
  
  persistance:
    enabled: true
    size: 1Gi

metrics:
  serviceMonitor:
    enabled: true
