{
 "title": "otus-demo",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "500 Exception Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[5m])",
     "legendFormat": "{{method}} {{uri}} ({{pod}})"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum[1m])/rate(http_server_requests_seconds_count[1m])) * 1000",
     "legendFormat": "{{uri}} latency, ms"
    }
   ]
  },
  {
   "title": "latency (0.9 quantile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \n      sum by (le, uri) \n         (rate(http_server_requests_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{uri}} latency, ms"
    }
   ]
  },
  {
   "title": "latency (0.5 quantile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, uri) \n         (rate(http_server_requests_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{uri}} latency, ms"
    }
   ]
  },
  {
   "title": "latency (max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, uri) \n         (rate(http_server_requests_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{uri}} latency, ms"
    }
   ]
  },
  {
   "title": "latency (0.99 quantile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, uri) \n         (rate(http_server_requests_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "{{uri}} latency, ms"
    }
   ]
  }
 ]
}