{
 "title": "postgres",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PG UP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_database_size_bytes" }
   ]
  },
  {
   "title": "seq_scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan[1m])"
    }
   ]
  },
  {
   "title": "inserts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins[1m])"
    }
   ]
  },
  {
   "title": "updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd[1m])"
    }
   ]
  },
  {
   "title": "deletes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del[1m])"
    }
   ]
  }
 ]
}